matrix:
  include:
    - os: linux
      language: python
      python: "3.7"

services:
  - xvfb

before_install:
  - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - sh travis.sh bootstrap

script:
  - flake8 --ignore=E501,W291,E722,E226,F401
  - sh travis.sh run_tests
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 17641d65-2d77-4153-aa62-6e0d013e1c44
