matrix:
  include:
    - os: linux
      language: python

services:
  - xvfb

before_install:
  - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install flake8==3.5
  - sh travis.sh bootstrap

script:
  - flake8 --ignore=E501,W291,E722,E226
  - sh travis.sh run_tests
#  - pytest --flake8
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 17641d65-2d77-4153-aa62-6e0d013e1c44
