language: python
python: "3.7"

services:
  - xvfb

before_install:
  - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
  - sudo apt-get install -y kcov
  - sh travis.sh bootstrap

script:
  - flake8 --ignore=E501,W291,E722,E226,F401
  - coverage run test/periodic.py
  - bash <(curl -s https://codecov.io/bash) -t 17641d65-2d77-4153-aa62-6e0d013e1c44
  - sh travis.sh run_tests
#  - mkdir -p coverage && kcov coverage travis.sh
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 17641d65-2d77-4153-aa62-6e0d013e1c44
